---
title: "Upset Plot Generation"
output:
  workflowr::wflow_html:
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: hide
editor_options:
  chunk_output_type: console
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r, load-libs}
library(tidyverse)
library(ComplexUpset)
library(biomaRt)
library(ggthemes)
library(ggpubr)

movies = as.data.frame(ggplot2movies::movies)
genres = colnames(movies)[18:24]
movies[genres] = movies[genres] == 1
movies[movies$mpaa == '', 'mpaa'] = NA
movies = na.omit(movies)
upset(movies, genres, name='genre', width_ratio=0.1)
```

```{r, degs}
load("output/condition-analysis.RData")
samples = colnames(counts)
df <- filtered_counts
df[samples] = df[samples] > 10
df = na.omit(df)
upset(df, samples, name='sample', width_ratio=0.1)
ggsave("output/bysample_upset.png", scale = 1, width = 18, height = 12, units = "in")
```






```{r, annotate}
#unannotated <- res_aff_vs_unaff_df_genename %>% filter(str_detect(gene_name, "ENS"))
#ensembl_genes <- useEnsembl(biomart = "genes", dataset = "hsapiens_gene_ensembl")
#ensembl_reg <- useEnsembl(biomart = "regulation", dataset = "hsapiens_mirna_target_feature")

#unanno_annotated <- getBM(attributes = c('ensembl_gene_id_version', 'mirbase_accession', 'hgnc_symbol', 'entrezgene_id'),
#      values = unannotated$Ensembl_ID,
#      filters = "ensembl_gene_id_version",
#      mart = ensembl_genes)
```


```{r, vars}
# # Pivot the data
# pivot_df <- vars_of_interest %>%
#   group_by(RNA_Samples_id, Gene) %>%
#   summarise(has_gene = any(!is.na(Gene))) %>%
#   spread(key = Gene, value = has_gene, fill = FALSE)
# 
# pivot_df <- pivot_df %>%
#   dplyr::select(-1, -ncol(pivot_df))
# 
# genes <- colnames(pivot_df)
# genes <- genes[-1]
# 
# merged_df <- inner_join(pivot_df, vars_of_interest, by = "RNA_Samples_id")
# 
# # Extract the RNA_Samples_id column (assuming it's the first column)
# rna_samples_id <- merged_df$RNA_Samples_id
# 
# # Remove the RNA_Samples_id column and transpose the remaining data
# transposed_df <- t(merged_df[, -1])
# 
# # Convert the matrix back to a data frame
# transposed_df <- as.data.frame(transposed_df)
# 
# # Set the column names to RNA_Samples_id
# colnames(transposed_df) <- rna_samples_id
# 
# # Remove duplicate columns
# transposed_df <- transposed_df[, !duplicated(as.list(transposed_df))]
# 
# # Only keep genes
# filtered_df <- transposed_df[rownames(transposed_df) %in% genes, ]
# 
# upset(filtered_df, samples, name='Sample',
#     width_ratio=0.1) + theme_fivethirtyeight()
# ggsave("output/gene_interest_upset.png", scale = 1, width = 18, height = 14, units = "in")
# upset(merged_df, Gene,
#       annotations = list(
#         'Affected Status'=(
#             ggplot(mapping=aes(fill=Affected))
#             + geom_bar(stat='count', position='fill')
#             + scale_y_continuous(labels=scales::percent_format())
#             + scale_fill_manual(values=c(
#                 'Yes'='#E41A1C', 'No'='#377EB8',
#             ))
#             + ylab('Affected Status')
#         )
#     ),
#     width_ratio=0.1) + theme_fivethirtyeight()
```
